// portfolio.client.angular/src/app/shared/components/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, Routes } from '@angular/router';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.scss'],
})
export class NavBarComponent implements OnInit {
  constructor(public router: Router) {}
  // TODO: de routes bekomen van de router
  // kan via router.config, maar ook nog eens uitzoeken hoe je aan de routes van submodules komt...
  routes: Routes = [
    {
      path: 'about-me',
      title: 'About me',
      data: { nav: true },
    },
    {
      path: 'blog',
      title: 'Blog',
      data: { nav: true },
    },
  ];


  ngOnInit() {
    // this.router.config.forEach((i) => {
    //   this.getPaths(i);
    // });
    // console.log(this.urls);
  }

  // urls: string[] = [];
  // getPaths(route: Route, parent: string = '') {
  //   if (route.redirectTo) {
  //     return;
  //   }
  //   if (route.children) {
  //     route.children.forEach((i) => {
  //       this.getPaths(i, parent + route.path);
  //     });
  //   } else if (route.loadChildren) {
  //     (<any>this.router).configLoader
  //       .load(this.injector, route)
  //       .subscribe((i: any) => {
  //         i.routes.forEach((j: any) => {
  //           this.getPaths(j, parent + route.path);
  //         });
  //       });
  //   } else if (route.path != null) {
  //     this.setPath(route.path, parent);
  //   }
  // }
  // setPath(path: any, parent: any) {
  //   let fullPath: string = '';
  //   if (path != null) {
  //     if (parent) {
  //       fullPath = `/${parent}/${path}`;
  //     } else {
  //       fullPath = `/${path}`;
  //     }
  //   }
  //   this.urls.push(fullPath);
  // }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid mx-3">
    <a class="navbar-brand" href="#"
      ><img src="assets/images/wordart.png" height="40"
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav" *ngFor="let row of routes">
        <a
          *ngIf="row.data?.['nav']"
          routerLinkActive="active"
          class="nav-link"
          [routerLink]="row.path"
          >{{ row.title }}</a
        >
      </div>
    </div>
  </div>
</nav>

// portfolio.client/src/components/Navbar.vue
<script setup lang="ts">
import { useRoute, useRouter } from "vue-router";

const router = useRouter();
const currentRoute = useRoute();
// Filter out non visible routes
const routes = router.getRoutes().filter((e) => e.meta.nav);
</script>

<template>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid mx-3">
      <a class="navbar-brand" href="#">
        <img src="@/assets/images/wordart.png" height="40" />
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav" v-for="route of routes" :key="route.path">
          <router-link :to="route.path" class="nav-item nav-link" :class="{ active: currentRoute.name == route.name }">{{
            route.meta.title }}
          </router-link>
        </div>
      </div>
    </div>
  </nav>
</template>
