// portfolio.client.angular/src/app/modules/portfolio/elements/postcard/postcard.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Post } from 'src/app/shared/models/post.model';

@Component({
  selector: 'app-postcard',
  templateUrl: './postcard.component.html',
  styleUrls: ['./postcard.component.scss'],
})
export class PostcardComponent implements OnInit {
  @Input()
  post!: Post; //Je moet blijkbaar expliciet meegeven dat post niet null zal zijn.
  constructor() {}

  ngOnInit(): void {
    if (this.post == null) {
      console.error('Post mag geen NULL zijn');
    }
  }
}

<div
  class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
>
  <div class="col p-4 d-flex flex-column position-static">
    <strong class="d-inline-block mb-2 text-success">{{
      post.blogType
    }}</strong>
    <h3 class="mb-0">{{ post.postTitle }}</h3>
    <div class="mb-1 text-muted">{{ post.createdDate | date: "short" }}</div>
    <p class="mb-auto">{{ post.short }}</p>
    <a
      route-href="route: blogpost; params.bind: {id:post.id}"
      class="stretched-link"
    >
      Continue reading</a
    >
  </div>
  <div class="col-auto d-none d-lg-block">
    <img
      style="object-fit: cover"
      width="150"
      height="100%"
      src="{{ post.thumbnail }}"
      alt="thumbnail"
      focusable="false"
    />
  </div>
</div>

// portfolio.client/src/components/PostCard.vue
<script setup lang="ts">
</script>

<template>
  <!-- <require from="../value-converters/date-format-value-converter"></require> -->
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-success">${post.blogType}</strong>
      <h3 class="mb-0">${post.postTitle}</h3>
      <div class="mb-1 text-muted">${post.createdDate}</div>
      <p class="mb-auto">${post.short}</p>
      <a route-href="route: blogpost; params.bind: {id:post.id}" class="stretched-link">
        Continue reading</a>
    </div>
    <div class="col-auto d-none d-lg-block">
      <img style="object-fit: cover" width="150" height="100%" src="${post.thumbnail}" alt="thumbnail"
        focusable="false" />
    </div>
  </div>
</template>

<style></style>
